import { defineProblem, type TestCase } from '@/features/practice'

/** Edge cases and random inputs; expected outputs come from a brute-force simulation. */
// prettier-ignore
const hiddenTests: TestCase[] = [
  { args: ["A"], expected: "A" },
  { args: ["B"], expected: "B" },
  { args: ["AB"], expected: "" },
  { args: ["CD"], expected: "" },
  { args: ["BA"], expected: "BA" },
  { args: ["DC"], expected: "DC" },
  { args: ["ABCD"], expected: "" },
  { args: ["ACDB"], expected: "" },
  { args: ["AABB"], expected: "" },
  { args: ["CCDD"], expected: "" },
  { args: ["ACBD"], expected: "ACBD" },
  { args: ["ZZZ"], expected: "ZZZ" },
  { args: ["ABABABAB"], expected: "" },
  { args: ["AABBCCDD"], expected: "" },
  { args: ["CACBDD"], expected: "CACBDD" },
  { args: ["ABXCD"], expected: "X" },
  { args: ["DCBA"], expected: "DCBA" },
  { args: ["BACAD"], expected: "BACAD" },
  { args: ["DDDBADAD"], expected: "DDDBADAD" },
  { args: ["DADCBACAAAAD"], expected: "DADCBACAAAAD" },
  { args: ["BDABDDBCBBDCADABCACD"], expected: "BDDDBCBBDCADCA" },
  { args: ["BCCDDADBDDBCCADABDCDADACDBBBABBDCCDCADBB"], expected: "BADBDDBCCADDADBBBDCCADBB" },
  { args: ["DADCBDDCDCACDABBBACAAAADACBCABCCABBCBCCDCDDAACDCDBCACBDABADBABDDBDBADCDACBBACAACCBDCBAABDBADBCABDBDA"], expected: "DADCBDDCBACAAAADACBCCCBCBACACBDADBDDBDBADACBBACAACCBDCBADBADBBDA" },
  { args: ["DCEDACEDCABBCEBCDBCADECEDEBAAABBBEBCCEECCCCACBEDBEEACADADBBCAEEDAEEBEACCCEEADCAACAEAADAABBEDBADBBBADDECECDCABCAAACECDDCDAACEDACBEEDCCBEBCBBCACADAECBDCACBCECBCAEEEEABBABDACEAAAACCDDBAECAEBBBBCCAEECBBBEACEEBBCDEBABCADDECEDEDADCBCDADEAACEBEBBCCDEDBEABDABECEDBBCDDBDCEECBAAECBEBCCCECBDEAAEEEDBBCDBEADDCDE"], expected: "DCEDACEDCBCEBBCADECEDEBEBCCEECCCCACBEDBEEACADADBBCAEEDAEEBEACCCEEADCAACAEAADEDBADBBBADDECECCAAACEDAACEDACBEEDCCBEBCBBCACADAECBDCACBCECBCAEEEEBDACEAAAAECAEBBBBCCAEECBBBEACEEBBEBCADDECEDEDADCBADEAACEBEBBCEDBEDECEDBBDBDCEECBAAECBEBCCCECBDEAAEEEDBBBEADDE" },
  { args: ["BEAEACACABEADBDDDBCDBEDBADEEDACCBDEABEDEAAEBCBBCBEBCCECDBECDDABEDBCAAAEAECBAECECDECECAADDCCEDCEDADDBEACEEBDEEDCBDEEBCEADEDDCEEADBCADBDCBAEACCDECBDCDBDEACEAEDACADABEBADCECBEBBCCAAECDEEABCECCEBDEDBDCECBCEBAEDCDBCBABEDEBECDEBBBDCCDBABCAABDCDABAAEABADEEDCCAEBABDBDDDBBBCDEEDBDCCDEABAAAADCDECBDBBAADBEAEDCBADCAAEAEBACADABADBCBDDCCCBBAEEBCDEEEACEDEBEDACEACBABABDAAAEDECACABEADBDDAECACCACADACCBCDACADBEEBCCEDEDABDEEEEEACBBCDECADCBEAACECDCCCCCEEAEABCCCEADCDDCDAEABAEDECBECCCDCDECEEBABCBEBABDEAAECABCAEEAABBEDAECDCBBEDBDDCEBDACDBAEDEDADEEEEDACDABCAEACECEEECEDEEDEECDCBEDEBEBCADEACDDCAAAADCDCCDCDDADCBDBABCCBECDCECDCDCDBDDDAABBBBAACBDADBAADEAEBEDCAAEDACCBDABADADCEDDAEDABDEBBECDECDEBECDAACCAEDCABECCBDBBCBDEEAEEEBDCCDCCDBDCEDBCBEBEDEBAECEBBCEDDCABBCBAEAEBABEBEECDCAACEBABCCCEEDAACCBACBEACAAACCBCEACAABDCBACCAECACBECDAEEEDEDEDCBCEBAEEABBBDCEACECECDBDACAECEEEEAECDBBAEBBDCCCBBDDDAEBCCEAEABDEADADEDCCDDEDAADAAAAEBEECECECDBEBAECBAACDCCAEDDDCCCDBEEBACAEBEDCAEADBDBDBABCCBDDCDBDDDEAEDCBBADDAAABDDECBBEACADDBEDAEBDBBC"], expected: "BEAEACACEADBDDDBBEDBADEEDACCBDEEDEAAEBCBBCBEBCCEBEDEDBCAAAEAECBAECEECECAADDCCEDCEDADDBEACEEBDEEDCBDEEBCEADEDDCEEADBCADBDCBAEACECBDBDEACEAEDACADEBADCECBEBBCCAAEEECECCEBDEDBDCECBCEBAEDBCBEDEBEEBBBDCBCADAAEADEEDCCAEBDBDDDBBBEEDBDCEAAAADECBDBBAADBEAEDCBADCAAEAEBACADADBCBDDCCCBBAEEBEEEACEDEBEDACEACBDAAAEDECACEADBDDAECACCACADACCBACADBEEBCCEDEDDEEEEEACBBECADCBEAACECCCCCEEAECCCEADDAEAEDECBECCECEEBCBEBDEAAECCAEEEDAECBBEDBDDCEBDAEDEDADEEEEDACAEACECEEECEDEEDEECBEDEBEBCADEADCAAAADADCBDBCCBECEBDDDBBAACBDADBAADEAEBEDCAAEDACCBDADADCEDDAEDDEBBEEEBEAACCAEDCECCBDBBCBDEEAEEEBDCCBDCEDBCBEBEDEBAECEBBCEDDCBCBAEAEBEBEECAACEBCCCEEDAACCBACBEACAAACCBCEACADCBACCAECACBEAEEEDEDEDCBCEBAEEBBDCEACECEBDACAECEEEEAEBBAEBBDCCCBBDDDAEBCCEAEDEADADEDEDAADAAAAEBEECECEBEBAECBAACCAEDDDCCBEEBACAEBEDCAEADBDBDBCCBDDBDDDEAEDCBBADDAADDECBBEACADDBEDAEBDBBC" },
  { args: ["CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDXABABABABABABABABABABABABABABABABABABABAB"], expected: "X" },
]

export default defineProblem({
  signature: {
    kind: 'function',
    name: 'removePairs',
    params: [{ name: 's', type: 'string' }],
    returns: 'string',
  },
  examples: [
    {
      args: ['ABFCACDB'],
      expected: 'FC',
      explanation:
        'Remove "AB" to get "FCACDB", then "CD" to get "FCAB", then "AB" to get "FC". No pair is left.',
    },
    {
      args: ['CABD'],
      expected: '',
      explanation: 'Removing "AB" joins "C" and "D" into a new pair, so everything is removed.',
    },
    { args: ['ACBBD'], expected: 'ACBBD', explanation: 'There is no "AB" or "CD" to remove.' },
  ],
  tests: [
    ...hiddenTests,
    // Deeply nested pairs: removing one pair at a time and rescanning is quadratic.
    { args: ['A'.repeat(20_000) + 'B'.repeat(20_000)], expected: '' },
    { args: ['C'.repeat(15_000) + 'AB'.repeat(5_000) + 'D'.repeat(15_000)], expected: '' },
  ],
  solution: {
    javascript: `function removePairs(s) {
  const stack = []
  for (const ch of s) {
    const top = stack[stack.length - 1]
    if ((top === 'A' && ch === 'B') || (top === 'C' && ch === 'D')) stack.pop()
    else stack.push(ch)
  }
  return stack.join('')
}`,
    python: `class Solution:
    def removePairs(self, s: str) -> str:
        stack = []
        for ch in s:
            if stack and stack[-1] + ch in ("AB", "CD"):
                stack.pop()
            else:
                stack.append(ch)
        return "".join(stack)`,
  },
})
