import { chapter, lesson, part, quiz, type CourseMeta, type Part } from '@/features/courses'

export const meta: CourseMeta = {
  id: 'system-design',
  title: 'System Design Mastery',
  subtitle:
    'From building blocks to real-world designs — prepare for system design interviews and beyond.',
  description:
    'A hands-on, text-first course on designing large-scale distributed systems. Learn the fundamentals, master ' +
    'the building blocks every system is made of, then apply them to more than twenty real-world design problems ' +
    'using a repeatable interview framework. Every lesson ends with a quiz so you can check your understanding.',
  level: 'Intermediate',
  highlights: [
    'A repeatable framework (SCALED) for tackling any system design interview',
    'Back-of-the-envelope estimation for servers, storage and bandwidth',
    'Core building blocks: DNS, load balancers, databases, caches, queues, CDNs and more',
    'Consistency models, replication, partitioning and fault-tolerance trade-offs',
    'Designing video platforms, ride-hailing, messaging, maps, feeds and payment systems',
    'System design for AI products: LLM serving, RAG and data infrastructure',
    'Lessons from real-world outages and how to design for failure',
    'How to communicate and defend trade-offs like a senior engineer',
  ],
}

export const parts: Part[] = [
  part('foundations', 'Part I · Foundations', [
    chapter('introduction', 'Introduction', [
      lesson('welcome', 'Welcome to System Design Mastery'),
      lesson('why-system-design', 'Why Every Engineer Should Learn System Design'),
      lesson('course-structure', 'How This Course Is Organized'),
    ]),
    chapter('interviews', 'The System Design Interview', [
      lesson('preparing', 'Preparing for the System Design Interview'),
      lesson('dos-and-donts', 'Do’s and Don’ts of the Interview'),
      lesson('common-traps', 'Common Interview Traps and How to Avoid Them'),
      lesson('preparation-timeline', 'How Long Should You Prepare?'),
      lesson('scaled-framework', 'The SCALED Framework'),
      lesson('mock-interview', 'A Mock Interview, Start to Finish'),
      quiz('quiz', 'Quiz: The System Design Interview'),
    ]),
    chapter('core-concepts', 'Core Concepts', [
      lesson('abstractions', 'Abstractions in System Design'),
      lesson('rpc', 'Network Abstractions: Remote Procedure Calls'),
      lesson('consistency-models', 'The Spectrum of Consistency Models'),
      lesson('failure-models', 'The Spectrum of Failure Models'),
      quiz('quiz', 'Quiz: Core Concepts'),
    ]),
    chapter('non-functional', 'Non-Functional Characteristics', [
      lesson('availability', 'Availability'),
      lesson('reliability', 'Reliability'),
      lesson('scalability', 'Scalability'),
      lesson('maintainability', 'Maintainability'),
      lesson('fault-tolerance', 'Fault Tolerance'),
      lesson('nfrs-in-interviews', 'Non-Functional Requirements in Interviews'),
      quiz('quiz', 'Quiz: Non-Functional Characteristics'),
    ]),
    chapter('estimation', 'Back-of-the-Envelope Estimation', [
      lesson('numbers-to-know', 'Numbers Every Engineer Should Know'),
      lesson('resource-estimation', 'Worked Resource Estimation Examples'),
      quiz('quiz', 'Quiz: Estimation'),
    ]),
  ]),

  part('building-blocks', 'Part II · Building Blocks', [
    chapter('building-blocks-intro', 'Building Blocks Overview', [
      lesson('overview', 'Introduction to Building Blocks'),
    ]),
    chapter('dns', 'Domain Name System', [
      lesson('introduction', 'Introduction to DNS'),
      lesson('how-dns-works', 'How DNS Resolution Works'),
      quiz('quiz', 'Quiz: Domain Name System'),
    ]),
    chapter('load-balancers', 'Load Balancers', [
      lesson('introduction', 'Introduction to Load Balancers'),
      lesson('global-and-local', 'Global and Local Load Balancing'),
      lesson('advanced-details', 'Load Balancing Algorithms and Advanced Details'),
      quiz('quiz', 'Quiz: Load Balancers'),
    ]),
    chapter('databases', 'Databases', [
      lesson('introduction', 'Introduction to Databases'),
      lesson('types', 'Types of Databases'),
      lesson('replication', 'Data Replication'),
      lesson('partitioning', 'Data Partitioning'),
      lesson('trade-offs', 'Trade-offs in Databases'),
      quiz('quiz', 'Quiz: Databases'),
    ]),
    chapter('key-value-store', 'Key-Value Store', [
      lesson('overview', 'Designing a Key-Value Store'),
      lesson('design', 'Core Design of a Key-Value Store'),
      lesson('scalability-replication', 'Scalability and Replication'),
      lesson('versioning', 'Versioning Data and Tunable Consistency'),
      lesson('fault-tolerance', 'Fault Tolerance and Failure Detection'),
      quiz('quiz', 'Quiz: Key-Value Store'),
    ]),
    chapter('cdn', 'Content Delivery Network', [
      lesson('overview', 'Designing a CDN'),
      lesson('introduction', 'Introduction to CDNs'),
      lesson('design', 'Design of a CDN'),
      lesson('deep-dive-caching', 'CDN Deep Dive: Content Caching Strategies'),
      lesson('deep-dive-routing', 'CDN Deep Dive: Request Routing and Consistency'),
      lesson('evaluation', 'Evaluating the CDN Design'),
      quiz('quiz', 'Quiz: Content Delivery Network'),
    ]),
    chapter('sequencer', 'Sequencer', [
      lesson('overview', 'Designing a Unique ID Generator'),
      lesson('design', 'Unique ID Generator Designs'),
      lesson('causality', 'Unique IDs with Causality'),
      quiz('quiz', 'Quiz: Sequencer'),
    ]),
    chapter('monitoring', 'Distributed Monitoring', [
      lesson('overview', 'Designing Distributed Monitoring'),
      lesson('introduction', 'Introduction to Distributed Monitoring'),
      lesson('prerequisites', 'Prerequisites of a Monitoring System'),
      quiz('quiz', 'Quiz: Distributed Monitoring'),
    ]),
    chapter('server-monitoring', 'Monitoring Server-Side Errors', [
      lesson('design', 'Design of a Monitoring System'),
      lesson('detailed-design', 'Detailed Design of a Monitoring System'),
      lesson('visualization', 'Visualizing Monitoring Data'),
      quiz('quiz', 'Quiz: Server-Side Monitoring'),
    ]),
    chapter('client-monitoring', 'Monitoring Client-Side Errors', [
      lesson('client-side-errors', 'Focusing on Client-Side Errors'),
      lesson('design', 'Design of a Client-Side Monitoring System'),
      quiz('quiz', 'Quiz: Client-Side Monitoring'),
    ]),
    chapter('distributed-cache', 'Distributed Cache', [
      lesson('overview', 'Designing a Distributed Cache'),
      lesson('background', 'Caching Fundamentals'),
      lesson('high-level-design', 'High-Level Design of a Distributed Cache'),
      lesson('detailed-design', 'Detailed Design of a Distributed Cache'),
      lesson('evaluation', 'Evaluating the Distributed Cache'),
      lesson('memcached-vs-redis', 'Memcached versus Redis'),
      quiz('quiz', 'Quiz: Distributed Cache'),
    ]),
    chapter('messaging-queue', 'Distributed Messaging Queue', [
      lesson('overview', 'Designing a Distributed Messaging Queue'),
      lesson('requirements', 'Requirements of a Messaging Queue'),
      lesson('considerations', 'Design Considerations: Ordering and Delivery'),
      lesson('design-part-1', 'Design of a Messaging Queue: Part 1'),
      lesson('design-part-2', 'Design of a Messaging Queue: Part 2'),
      lesson('evaluation', 'Evaluating the Messaging Queue'),
      quiz('quiz', 'Quiz: Distributed Messaging Queue'),
    ]),
    chapter('pub-sub', 'Pub-Sub', [
      lesson('overview', 'The Pub-Sub Abstraction'),
      lesson('introduction', 'Introduction to Pub-Sub'),
      lesson('design', 'Design of a Pub-Sub System'),
      quiz('quiz', 'Quiz: Pub-Sub'),
    ]),
    chapter('rate-limiter', 'Rate Limiter', [
      lesson('overview', 'Designing a Rate Limiter'),
      lesson('requirements', 'Requirements of a Rate Limiter'),
      lesson('design', 'Design of a Rate Limiter'),
      lesson('algorithms', 'Rate Limiting Algorithms'),
      quiz('quiz', 'Quiz: Rate Limiter'),
    ]),
    chapter('blob-store', 'Blob Store', [
      lesson('overview', 'Designing a Blob Store'),
      lesson('requirements', 'Requirements of a Blob Store'),
      lesson('design', 'Design of a Blob Store'),
      lesson('considerations', 'Design Considerations of a Blob Store'),
      lesson('evaluation', 'Evaluating the Blob Store'),
      quiz('quiz', 'Quiz: Blob Store'),
    ]),
    chapter('distributed-search', 'Distributed Search', [
      lesson('overview', 'Designing Distributed Search'),
      lesson('requirements', 'Requirements of a Search System'),
      lesson('indexing', 'Indexing in Distributed Search'),
      lesson('design', 'Design of a Distributed Search System'),
      lesson('scaling', 'Scaling Search and Indexing'),
      lesson('evaluation', 'Evaluating the Search Design'),
      quiz('quiz', 'Quiz: Distributed Search'),
    ]),
    chapter('distributed-logging', 'Distributed Logging', [
      lesson('overview', 'Designing Distributed Logging'),
      lesson('introduction', 'Introduction to Distributed Logging'),
      lesson('design', 'Design of a Distributed Logging Service'),
      quiz('quiz', 'Quiz: Distributed Logging'),
    ]),
    chapter('task-scheduler', 'Distributed Task Scheduler', [
      lesson('overview', 'Designing a Distributed Task Scheduler'),
      lesson('requirements', 'Requirements of a Task Scheduler'),
      lesson('design', 'Design of a Distributed Task Scheduler'),
      lesson('considerations', 'Design Considerations of a Task Scheduler'),
      lesson('evaluation', 'Evaluating the Task Scheduler'),
      quiz('quiz', 'Quiz: Distributed Task Scheduler'),
    ]),
    chapter('sharded-counters', 'Sharded Counters', [
      lesson('overview', 'Designing Sharded Counters'),
      lesson('high-level-design', 'High-Level Design of Sharded Counters'),
      lesson('detailed-design', 'Detailed Design of Sharded Counters'),
      quiz('quiz', 'Quiz: Sharded Counters'),
    ]),
    chapter('building-blocks-wrap-up', 'Building Blocks Wrap-Up', [
      lesson('ecommerce-exercise', 'Exercise: Building Blocks of an E-Commerce Platform'),
      lesson('education-exercise', 'Exercise: Building Blocks of an Online Learning Platform'),
      lesson('wrapping-up', 'Wrapping Up the Building Blocks'),
      lesson('applying-scaled', 'Applying SCALED to Design Problems'),
    ]),
  ]),

  part('design-problems', 'Part III · Design Problems', [
    chapter('video-platform', 'Design a Video Platform (YouTube)', [
      lesson('overview', 'System Design: Video Platform'),
      lesson('requirements', 'Requirements of a Video Platform'),
      lesson('design', 'Design of a Video Platform'),
      lesson('evaluation', 'Evaluating the Video Platform Design'),
      lesson('real-world', 'The Reality Is More Complicated'),
      lesson('short-video-exercise', 'Exercise: Designing a Short-Video App'),
      quiz('quiz', 'Quiz: Video Platform'),
    ]),
    chapter('qa-platform', 'Design a Q&A Platform (Quora)', [
      lesson('overview', 'System Design: Q&A Platform'),
      lesson('requirements', 'Requirements of a Q&A Platform'),
      lesson('initial-design', 'Initial Design of a Q&A Platform'),
      lesson('final-design', 'Final Design of a Q&A Platform'),
      lesson('evaluation', 'Evaluating the Q&A Platform Design'),
      quiz('quiz', 'Quiz: Q&A Platform'),
    ]),
    chapter('maps', 'Design a Maps Service (Google Maps)', [
      lesson('overview', 'System Design: Maps and Navigation'),
      lesson('requirements', 'Requirements of a Maps Service'),
      lesson('design', 'Design of a Maps Service'),
      lesson('challenges', 'Challenges of a Maps Service'),
      lesson('detailed-design', 'Detailed Design of a Maps Service'),
      lesson('evaluation', 'Evaluating the Maps Design'),
      quiz('quiz', 'Quiz: Maps Service'),
    ]),
    chapter('proximity-service', 'Design a Proximity Service (Yelp)', [
      lesson('overview', 'System Design: Proximity Service'),
      lesson('requirements', 'Requirements of a Proximity Service'),
      lesson('design', 'Design of a Proximity Service'),
      lesson('considerations', 'Design Considerations: Geohashes and Quadtrees'),
      quiz('quiz', 'Quiz: Proximity Service'),
    ]),
    chapter('ride-hailing', 'Design a Ride-Hailing Service (Uber)', [
      lesson('overview', 'System Design: Ride-Hailing'),
      lesson('requirements', 'Requirements of a Ride-Hailing Service'),
      lesson('high-level-design', 'High-Level Design of a Ride-Hailing Service'),
      lesson('detailed-design', 'Detailed Design of a Ride-Hailing Service'),
      lesson('payments-fraud', 'Payments and Fraud Detection'),
      lesson('evaluation', 'Evaluating the Ride-Hailing Design'),
      lesson('food-delivery-exercise', 'Exercise: Designing Food Delivery'),
      quiz('quiz', 'Quiz: Ride-Hailing'),
    ]),
    chapter('microblogging', 'Design a Microblogging Service (Twitter)', [
      lesson('overview', 'System Design: Microblogging'),
      lesson('requirements', 'Requirements of a Microblogging Service'),
      lesson('high-level-design', 'High-Level Design of a Microblogging Service'),
      lesson('detailed-design', 'Detailed Design of a Microblogging Service'),
      lesson('client-side-load-balancing', 'Client-Side Load Balancing'),
      quiz('quiz', 'Quiz: Microblogging'),
    ]),
    chapter('newsfeed', 'Design a Newsfeed System', [
      lesson('overview', 'System Design: Newsfeed'),
      lesson('requirements', 'Requirements of a Newsfeed System'),
      lesson('design', 'Design of a Newsfeed System'),
      lesson('fanout-ranking', 'Fan-out and Ranking Deep Dive'),
      lesson('evaluation', 'Evaluating the Newsfeed Design'),
      quiz('quiz', 'Quiz: Newsfeed'),
    ]),
    chapter('photo-sharing', 'Design a Photo-Sharing Service (Instagram)', [
      lesson('overview', 'System Design: Photo Sharing'),
      lesson('requirements', 'Requirements of a Photo-Sharing Service'),
      lesson('design', 'Design of a Photo-Sharing Service'),
      lesson('detailed-design', 'Detailed Design of a Photo-Sharing Service'),
      lesson('evaluation', 'Evaluating the Photo-Sharing Design'),
      quiz('quiz', 'Quiz: Photo Sharing'),
    ]),
    chapter('url-shortener', 'Design a URL Shortener (TinyURL)', [
      lesson('overview', 'System Design: URL Shortener'),
      lesson('requirements', 'Requirements and Estimation'),
      lesson('design', 'Design: Encoding and Key Generation'),
      lesson('evaluation', 'Evaluating the URL Shortener'),
      quiz('quiz', 'Quiz: URL Shortener'),
    ]),
    chapter('web-crawler', 'Design a Web Crawler', [
      lesson('requirements', 'Requirements of a Web Crawler'),
      lesson('design', 'Design of a Web Crawler'),
      lesson('evaluation', 'Politeness, Deduplication and Crawler Traps'),
      quiz('quiz', 'Quiz: Web Crawler'),
    ]),
    chapter('messaging-app', 'Design a Messaging App (WhatsApp)', [
      lesson('overview', 'System Design: Messaging App'),
      lesson('requirements', 'Requirements of a Messaging App'),
      lesson('high-level-design', 'High-Level Design of a Messaging App'),
      lesson('detailed-design', 'Detailed Design of a Messaging App'),
      lesson('evaluation', 'Evaluating the Messaging App Design'),
      quiz('quiz', 'Quiz: Messaging App'),
    ]),
    chapter('typeahead', 'Design Typeahead Suggestions', [
      lesson('overview', 'System Design: Typeahead Suggestions'),
      lesson('requirements', 'Requirements of Typeahead Suggestions'),
      lesson('high-level-design', 'High-Level Design of Typeahead'),
      lesson('trie', 'Data Structure for Storing Prefixes'),
      lesson('detailed-design', 'Detailed Design of Typeahead'),
      lesson('evaluation', 'Evaluating the Typeahead Design'),
      quiz('quiz', 'Quiz: Typeahead Suggestions'),
    ]),
    chapter('collaborative-editing', 'Design Collaborative Editing (Google Docs)', [
      lesson('overview', 'System Design: Collaborative Editing'),
      lesson('requirements', 'Requirements of Collaborative Editing'),
      lesson('design', 'Design of a Collaborative Editor'),
      lesson('concurrency', 'Concurrency: OT versus CRDTs'),
      lesson('evaluation', 'Evaluating the Collaborative Editor'),
      quiz('quiz', 'Quiz: Collaborative Editing'),
    ]),
    chapter('deployment-system', 'Design a Code Deployment System', [
      lesson('introduction', 'Introduction to Code Deployment Systems'),
      lesson('design', 'Design of a Code Deployment System'),
      quiz('quiz', 'Quiz: Code Deployment System'),
    ]),
    chapter('payment-system', 'Design a Payment System', [
      lesson('introduction', 'Introduction to Payment Systems'),
      lesson('design', 'Design of a Payment System'),
      quiz('quiz', 'Quiz: Payment System'),
    ]),
    chapter('online-judge', 'Design an Online Judge (LeetCode)', [
      lesson('introduction', 'Introduction to Online Judges'),
      lesson('design', 'Design of an Online Judge'),
      quiz('quiz', 'Quiz: Online Judge'),
    ]),
    chapter('case-studies', 'More Case Studies', [
      lesson('cloud-file-storage', 'Design Cloud File Storage (Dropbox)'),
      lesson('ticket-booking', 'Design a Ticket Booking System (Ticketmaster)'),
      lesson('pastebin', 'Design a Text-Sharing Service (Pastebin)'),
      lesson('year-in-review', 'Scaling a Year-in-Review Feature'),
      lesson('flash-sale', 'Surviving Flash-Sale Traffic Spikes'),
      lesson('communication-apis', 'Building Communication APIs at Scale'),
      quiz('quiz', 'Quiz: Case Studies'),
    ]),
  ]),

  part('ai-systems', 'Part IV · AI-Era System Design', [
    chapter('ai-era', 'System Design in the AI Era', [
      lesson('how-ai-reshaped', 'How AI Reshaped System Design'),
      lesson('roles-and-tools', 'How Roles and Tools Changed the Interview'),
      lesson('ai-problems', 'Overview of AI Design Problems'),
    ]),
    chapter('llm-chat', 'Design a Conversational LLM Service (ChatGPT)', [
      lesson('requirements', 'Requirements of an LLM Chat Service'),
      lesson('design', 'Design of an LLM Chat Service'),
      quiz('quiz', 'Quiz: LLM Chat Service'),
    ]),
    chapter('ml-data-infra', 'Design Data Infrastructure for AI/ML', [
      lesson('overview', 'System Design: Data Infrastructure for AI/ML'),
      lesson('high-level-design', 'High-Level Design of ML Data Infrastructure'),
      lesson('detailed-design', 'Detailed Design of ML Data Infrastructure'),
      quiz('quiz', 'Quiz: ML Data Infrastructure'),
    ]),
    chapter('support-bot', 'Design an LLM Customer Support Bot', [
      lesson('requirements', 'Requirements of a Support Bot'),
      lesson('design', 'Design of a Support Bot with RAG'),
      quiz('quiz', 'Quiz: Support Bot'),
    ]),
    chapter('code-assistant', 'Design an AI Code Assistant', [
      lesson('requirements', 'Requirements of an AI Code Assistant'),
      lesson('design', 'Design of an AI Code Assistant'),
      quiz('quiz', 'Quiz: AI Code Assistant'),
    ]),
  ]),

  part('wrap-up', 'Part V · Lessons from Failures & Wrap-Up', [
    chapter('outages', 'Lessons from System Failures', [
      lesson('facebook-2021', 'The 2021 Facebook Outage'),
      lesson('kinesis-2020', 'The 2020 AWS Kinesis Outage'),
      lesson('us-east-1-2021', 'The 2021 AWS us-east-1 Outage'),
      quiz('quiz', 'Quiz: Lessons from Failures'),
    ]),
    chapter('conclusion', 'Concluding Remarks', [
      lesson('conclusions', 'Conclusions'),
      lesson('resources', 'Resources for Further Preparation'),
    ]),
    chapter('primer', 'Appendix: System Design Primer', [
      lesson('master-template', 'The SCALED Master Template'),
      lesson('primer', 'System Design Primer'),
      lesson('trade-offs', 'Distributed Systems Trade-offs'),
      lesson('key-concepts', 'Key Concepts Checklist'),
      lesson('scalable-systems-101', 'Scalable Systems 101'),
      lesson('low-latency', 'Best Practices for Low Latency'),
      lesson('design-patterns', 'Distributed System Design Patterns'),
      lesson('proxies', 'Proxies: Forward versus Reverse'),
      lesson('realtime-communication', 'Long Polling, WebSockets and Server-Sent Events'),
      lesson('cap-pacelc', 'CAP and PACELC Theorems'),
      lesson('consistent-hashing', 'Consistent Hashing'),
      lesson('indexes', 'Database Indexes'),
      lesson('analysis-vs-design', 'System Analysis versus System Design'),
      lesson('api-vs-system-design', 'API Design versus System Design Interviews'),
      quiz('final-assessment', 'Final Assessment'),
    ]),
  ]),
]
